import "../styles/globals.css";
import "rsuite/dist/rsuite.min.css";
import styles from "../styles/Home.module.css";
import { SessionProvider } from "next-auth/react";
import Navbar from "../components/Navbar";
import Head from "next/head";
import SideNav from "../components/SideNav";
import Image from "next/image";
import { GlobalProvider } from "../context/GlobalState";
function MyApp({ Component, pageProps }) {
  return (
    <SessionProvider session={pageProps.session}>
      <GlobalProvider>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main>
          {/* Nav Bar */}
          <div className={styles.navbar}>
            <div className={styles.navbar_item}>
              <Navbar />
            </div>
          </div>
          {/* Sider Bar */}
          <div style={{ display: "flex", width: "100%" }}>
            <div
              style={{
                height: "100%",
                justifyContent: "flex-start",
              }}
            >
              <SideNav />
            </div>
            {/* Content */}
            <div className={styles.container}>
              <div
                className={styles.main}
                style={{ width: "100%", height: "100%", padding: "20px 0" }}
              >
                <Component {...pageProps} />
              </div>
              <footer className={styles.footer}>
                <a
                  href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
                  target="_blank"
                  rel="noopener noreferrer"
                >
                  Powered by{" "}
                  <span className={styles.logo}>
                    <Image
                      src="/vercel.svg"
                      alt="Vercel Logo"
                      width={72}
                      height={16}
                    />
                  </span>
                </a>
              </footer>
            </div>
          </div>
        </main>
      </GlobalProvider>
    </SessionProvider>
  );
}

export default MyApp;
